"""empty message

Revision ID: af707dd0d450
Revises: a19075033509
Create Date: 2025-12-18 19:49:32.978534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af707dd0d450'
down_revision = 'a19075033509'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=220), nullable=False))
        batch_op.drop_column('decription')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('decription', sa.VARCHAR(length=220), nullable=False))
        batch_op.drop_column('description')

    # ### end Alembic commands ###
